name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter pub get
      
      - name: Ensure Podfile with iOS 13.0
        run: |
          cd ios
          if [ ! -f Podfile ]; then
            pod init
          fi
          if grep -q "^platform :ios" Podfile; then
            sed -i '' 's/^platform :ios.*/platform :ios, '\''13.0'\''/' Podfile
          else
            sed -i '' '1s;^;platform :ios, '\''13.0'\''\n;' Podfile
          fi

      - name: Install CocoaPods
        run: |
          cd ios
          pod install


      - name: Build archive and generate dSYM
        run: |
          # flutter build ios --release --no-codesign --build-name=1.1.0 --build-number=${{ github.run_number }}
          xcodebuild archive \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/ios/archive/Runner.xcarchive \
            CODE_SIGNING_ALLOWED=NO

      - name: Export IPA from archive
        run: |
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath build/ios/ipa

      - name: Print extracted Info.plist values
        run: |
          /usr/libexec/PlistBuddy -c "Print CFBundleVersion" build/ios/archive/Runner.xcarchive/Products/Applications/Runner.app/Info.plist
          /usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" build/ios/archive/Runner.xcarchive/Products/Applications/Runner.app/Info.plist

      - name: List generated dSYM files
        run: ls -R build/ios/archive/Runner.xcarchive/dSYMs

      - name: Upload dSYM to Firebase Crashlytics
        run: |
          ./ios/Pods/FirebaseCrashlytics/upload-symbols \
            -gsp ios/Runner/GoogleService-Info.plist \
            -p ios \
            --plist build/ios/archive/Runner.xcarchive/Products/Applications/Runner.app/Info.plist \
            build/ios/archive/Runner.xcarchive/dSYMs/Runner.app.dSYM

      - name: Dump UUID from dSYM
        run: |
          dwarfdump --uuid build/ios/archive/Runner.xcarchive/dSYMs/Runner.app.dSYM

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/ipa/Runner.ipa
          tag: v${{ github.run_number }}
          overwrite: true
          body: "This is first release"

      - name: Upload dSYM artifact
        uses: actions/upload-artifact@v4
        with:
          name: dSYM
          path: build/ios/archive/Runner.xcarchive/dSYMs/Runner.app.dSYM