name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter pub get
      
      - name: Ensure Podfile with iOS 13.0
        run: |
          cd ios
          if [ ! -f Podfile ]; then
            pod init
          fi
          if grep -q "^platform :ios" Podfile; then
            sed -i '' 's/^platform :ios.*/platform :ios, '\''13.0'\''/' Podfile
          else
            sed -i '' '1s;^;platform :ios, '\''13.0'\''\n;' Podfile
          fi

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      - name: Build archive and generate dSYM
        run: |
          flutter build ios --release --no-codesign --build-name=1.1.0 --build-number=${{ github.run_number }}

      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/ipa/Runner.ipa
          tag: v${{ github.run_number }}
          overwrite: true
          body: "This is first release"